### PR TITLE
Added Sharpen and Emboss Filter

### LINKED ISSUE #10: Sharpen And Emboss
I am Working on Sharpen and Emboss Filters

### PR DESCRIPTION
**Pull request by gargarchit**
Fixes #10 

Added Sharpen and Emboss Filter

### CODE REVIEW

**Comment by mgautam98** [comment]
Solve the conflict

**Comment by mgautam98** [comment]
For sharpen we want coloured image

**Comment by gargarchit** [comment]
Yeah Wait I am Correcting it

**Comment by gargarchit** [comment]
Okay then I will revert my Pull request and do this both for Color after that

**Comment by mgautam98** [comment]
image

**Pull request closed without merging**
